version: '3'

services:
  # Prometheus Configuration
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configurations/prom-config.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  
  # Loki Configuration
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/mnt/config/loki-config.yml
    volumes:
      - ./configurations/loki-config.yml:/mnt/config/loki-config.yml
      - ./loki:/wal

  # Grafana Configuration
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./configurations/grafana-datasources.yml:/etc/grafana/provisioning/datasources/grafana-datasources.yml
    depends_on:
      - loki
      - prometheus
