version: '3'

services:
  # Prometheus Configuration
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configurations/prom-config.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  
  # Loki Configuration
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/mnt/config/loki-config.yaml
    volumes:
      - ./configurations/loki-config.yml:/mnt/config/loki-config.yaml
      - ./loki/wal:/wal

  # Grafana Configuration
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./configurations/grafana-datasources.yml:/etc/grafana/provisioning/datasources/grafana-datasources.yml
      - ./configurations/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - loki
      - prometheus

  webapp-install: # install dependecies before start the app
    image: node:20
    command: "npm i --prefix app"
    volumes:
      - ./:/app
  webapp: # start the app
    image: node:20
    container_name: webapp
    command: "node app/index.js"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - webapp-install
